fix rerouting
Signed-off-by: slashexx <dhruvpuri.35@gmail.com>

diff --git a/backend/code-execution-service/Dockerfile b/backend/code-execution-service/Dockerfile
--- a/backend/code-execution-service/Dockerfile
+++ b/backend/code-execution-service/Dockerfile
@@ -1,19 +1,21 @@
 FROM golang:1.23-alpine
 
-
 ENV DEBIAN_FRONTEND=noninteractive
 
+# Install dependencies
 RUN apk add --no-cache \
     python3 \
     gcc \
     g++ \
     openjdk11 \
     bash \
-    rust \
-    cargo
+    curl
 
+RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
 
-RUN javac -version || echo "javac not found"
+ENV PATH="/root/.cargo/bin:${PATH}"
+
+RUN rustc --version || echo "rustc not found"
 
 WORKDIR /app
 
@@ -24,6 +26,6 @@ COPY . .
 
 RUN go build -o code-execution-service .
 
-EXPOSE 8081 
+EXPOSE 8081
 
 CMD ["./code-execution-service"]
